services:
  gateway:
    container_name: gateway
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - userservice
      - shelfsservice
      - outfitofferservice
    networks:
      - microservice_net

  userservice:
    container_name: user-service
    image: ${DOCKER_REGISTRY-}user-service
    build:
      context: .
      dockerfile: UserService/Dockerfile
    environment:
      - ConnectionStrings__Default=Host=onlineshelfdb;Database=onlineShelf_db;Username=admin;Password=admin
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - microservice_net

  shelfsservice:
    container_name: shelfs-service
    image: ${DOCKER_REGISTRY-}shelfs-service    
    build:
      context: .
      dockerfile: ShelfsService/Dockerfile
    environment:
      - ConnectionStrings__Default=Host=onlineshelfdb;Database=onlineShelf_db;Username=admin;Password=admin
    networks:
      - microservice_net

  outfitofferservice:
    container_name: outfit-offer-service
    image: ${DOCKER_REGISTRY-}outfit-offer-service
    build:
      context: .
      dockerfile: OutfitOfferService/Dockerfile
    environment:
      - ConnectionStrings__Default=Host=onlineshelfdb;Database=onlineShelf_db;Username=admin;Password=admin
    networks:
      - microservice_net

  onlineshelfdb:
    container_name: online-shelf-db
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: onlineShelf_db
      TZ: Europe/Kyiv
    ports:
      - "5432:5432"
    networks:
      - microservice_net

networks:
  microservice_net:
    driver: bridge