// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserService.src.UserService.Repository.EfCore;

#nullable disable

namespace UserService.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251116223657_AddUserRoleLinks")]
    partial class AddUserRoleLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("user-service")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserService.src.UserService.Repository.EfCore.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users", "user-service");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1437f42-8b54-4a02-b0a5-800426cd7580"),
                            DateCreated = new DateTime(2025, 10, 19, 18, 51, 4, 0, DateTimeKind.Utc),
                            Email = "admin@example.com",
                            EmailVerified = false,
                            Login = "admin",
                            PasswordHash = "AQAAAAIAAYagAAAAEI4cRC2MXQNNcCJCh2m1w+g452KVBfKKuXgrlc9nn8HCk64K8egBH3B8iRp0XSw5IQ==",
                            State = 0,
                            UpdatedAt = new DateTime(2025, 10, 19, 18, 51, 4, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("2c9d6f42-8b54-4a02-b0a5-800426cd7581"),
                            DateCreated = new DateTime(2025, 10, 19, 18, 51, 4, 0, DateTimeKind.Utc),
                            Email = "test@example.com",
                            EmailVerified = false,
                            Login = "test",
                            PasswordHash = "AQAAAAIAAYagAAAAEHkSP0s7Jv4tRM3HgLxrhmEkgwlxzDn+XHbbZjIVWUnGYIZWVEY5Zgmh0gpl6JAF4Q==",
                            State = 0,
                            UpdatedAt = new DateTime(2025, 10, 19, 18, 51, 4, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("UserService.src.UserService.Repository.EfCore.Entities.UserRoleLink", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "Role");

                    b.ToTable("UserRoleLink", "user-service");
                });

            modelBuilder.Entity("UserService.src.UserService.Repository.EfCore.Entities.UserRoleLink", b =>
                {
                    b.HasOne("UserService.src.UserService.Repository.EfCore.Entities.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserService.src.UserService.Repository.EfCore.Entities.User", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
