syntax = "proto3";

option csharp_namespace = "ImageService.Protos"; 

service ImageProcessor {
  // Метод для завантаження
  rpc UploadImage (UploadImageRequest) returns (UploadImageResponse);
  
  // Метод для видалення
  rpc DeleteImage (DeleteImageRequest) returns (DeleteImageResponse);
   
  // Метод для отримання фото за назвою
  rpc GetPhotoByName (GetPhotoRequest) returns (stream GetPhotoResponse);
}

// Запит на завантаження
message UploadImageRequest {
  bytes data = 1;
  string file_name = 2;
}

// Відповідь на завантаження
message UploadImageResponse {
  string big_image_name = 1;
  string small_image_name = 2;
  bool success = 3;
}

// Запит на видалення
message DeleteImageRequest {
  string big_image_name = 1;
  string small_image_name = 2;
}

// Відповідь на видалення
message DeleteImageResponse {
  bool success = 1;
}


// Запит на отримання
message GetPhotoRequest {
  string file_name = 1;
}

// Відповідь на отримання
message GetPhotoResponse {
  bytes chunk_data = 1;
}