// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShelfsService.src.ShelfsService.Repository.EfCore;

#nullable disable

namespace ShelfsService.Migrations
{
    [DbContext(typeof(ShelfsDataContext))]
    partial class ShelfsDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("shelf_service")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShelfsService.src.ShelfsService.Repository.EfCore.Entities.AttributeName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeKey")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Attributes", "shelf_service");
                });

            modelBuilder.Entity("ShelfsService.src.ShelfsService.Repository.EfCore.Entities.AttributesValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeId")
                        .HasColumnType("integer");

                    b.Property<int>("AttributeKey")
                        .HasColumnType("integer");

                    b.Property<string>("AttributeValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId");

                    b.ToTable("AttributesValues", "shelf_service");
                });

            modelBuilder.Entity("ShelfsService.src.ShelfsService.Repository.EfCore.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttributeColorMain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AttributeColorSecond")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AttributeMatterial")
                        .HasColumnType("integer");

                    b.Property<int>("AttributePattern")
                        .HasColumnType("integer");

                    b.Property<int>("AttributeSeason")
                        .HasColumnType("integer");

                    b.Property<int>("AttributeType")
                        .HasColumnType("integer");

                    b.Property<string>("BigImage")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ShelfId")
                        .HasColumnType("uuid");

                    b.Property<string>("SmallImage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("isFavorite")
                        .HasColumnType("boolean");

                    b.Property<string>("positionKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ShelfId");

                    b.ToTable("Items", "shelf_service");
                });

            modelBuilder.Entity("ShelfsService.src.ShelfsService.Repository.EfCore.Entities.Shelf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("positionKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Shelfs", "shelf_service");
                });

            modelBuilder.Entity("ShelfsService.src.ShelfsService.Repository.EfCore.Entities.AttributesValue", b =>
                {
                    b.HasOne("ShelfsService.src.ShelfsService.Repository.EfCore.Entities.AttributeName", "Attribute")
                        .WithMany("Values")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");
                });

            modelBuilder.Entity("ShelfsService.src.ShelfsService.Repository.EfCore.Entities.Item", b =>
                {
                    b.HasOne("ShelfsService.src.ShelfsService.Repository.EfCore.Entities.Shelf", "Shelf")
                        .WithMany("Items")
                        .HasForeignKey("ShelfId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Shelf");
                });

            modelBuilder.Entity("ShelfsService.src.ShelfsService.Repository.EfCore.Entities.AttributeName", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("ShelfsService.src.ShelfsService.Repository.EfCore.Entities.Shelf", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
